### ISSUE TITLE
Mission Intros have missing sound Version 3.1.0

### ISSUE THREAD

**Issue by stunner345** [Wargus/wargus#379] opened 2021-07-16 16:43 UTC
In this version most of the intro speeches before the missions have only half of the sound file, the last bit isn't playing ( for example in the first Alliance missions of Tides of Darkness and Beyond the Dark Portal )

**Comment by timfel** [comment] 2021-07-16 17:31
Duplicate of #127

**Closed by timfel** 2021-07-16 17:31 UTC
