### ISSUE TITLE
Buggy transports

### ISSUE THREAD

**Issue by MarkusRamikin** [Wargus/wargus#178] opened 2016-07-02 10:12 UTC
A transport can become bugged, where it won't move and will immediately eject any passengers that board it. 

No idea how it happens, but I'm including a savegame. 3 out of 4 transports in that one are buggy! Also including replay, although it quickly gets out of sync for me.

[buggy transport.sav.gz](https://github.com/Wargus/wargus/files/344500/buggy.transport.sav.gz)
[transport bug.zip](https://github.com/Wargus/wargus/files/344502/transport.bug.zip)

**Comment by SimoneStarace** [comment] 2021-03-28 17:29
#121 The bug is still present.

**Comment by timfel** [comment] 2021-06-20 19:32
Duplicate of #121

**Closed by timfel** 2021-06-20 19:32 UTC
