### ISSUE TITLE
Wrong tracknames on rip music

### ISSUE THREAD

**Issue by baco** [Wargus/wargus#198] opened 2016-07-23 06:12 UTC
When extracting using midi `Orc Briefing.mid` is the same file than `Human Briefing.mid` (tested witth `diff` command). When extracting CD tracks, `Orc Briefing.ogg` is not created at all and the game uses `Human Briefing.ogg` for the Horde briefing.

In the original game, the `Main Menu` theme is used as Horde briefing theme.

When using midi, `Orc Briefing.mid`should be the same file than `Main Menu.mid` and when using ogg, `Orc Briefing.ogg` should be extracted from track number 15, and it also should be used as the `Main Menu` theme.

**Comment by timfel** [comment] 2016-08-17 08:18
Thanks, this should be fixed.

**Closed** 2016-08-17 08:17 UTC

**Comment by Erenussocrates** [comment] 2016-08-24 19:40
@timfel, hello, did you have any fix for that yet? I did not patched my own game yet and I have the same problem.

**Comment by timfel** [comment] 2016-08-24 22:08
It should be fixed, but you'll have to run the extraction again.

**Comment by DinkyDyeAussie** [comment] 2016-08-24 23:10
I extracted the latest binary a few days ago and I have to say the the main menu music is still "I'm a medievil man" and none of the videos were exrracted because ffmpeg2theora2 is broken still. The midi music works as intended but the ogg music is all wacked out still.

**Comment by timfel** [comment] 2016-08-25 00:04
@DinkyDyeAussie this issue wasn't about the main menu music, and I can't remember right now if I touched that. This was just about the Orc Briefing being wrong. Are your ogg files for the orc briefing the same as the human briefing?

**Comment by Kintobor** [comment] 2016-08-25 07:38
Dinky still isn't a Medieval Man.

**Comment by Erenussocrates** [comment] 2016-09-01 22:06
run the extruction? What must I do?
