### ISSUE TITLE
Incompatible lua files error on second multiplayer game

### ISSUE THREAD

**Issue by Bomfunk** [Wargus/wargus#389] opened 2021-10-11 21:36 UTC
**Describe the bug**
After one multiplayer game is successfully played and another one is created, the client no longer can connect, getting the "Incompatible lua files" error, even though both games are the same version, and the data files were copied from one PC to another.

**To Reproduce**
1. Create a game and join it with a client.
2. Quit to menu on both Wargus instances.
3. Again create a game and try joining it with a client.
4. Observe the "Incompatible lua files" on the client.

**Expected behavior**
Successful connection.

**Screenshots and Logs**
Gathered logs: https://drive.google.com/file/d/1mc6GWZmkBgbsX9h3Crgd0XrG3ROnIxIZ/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: Windows 10 as server and Arch Linux as client
 - Version 3.1.2

**Comment by ipochto** [comment] 2021-10-12 07:12
Confirm that.
The problem is in the continuous lua-files checksum calculation. Every time when any lua-file is loaded checksum is updated. And you will be able to join only if both of client and host checksums are equal. But if order of loading of lua-files inconsistent on both machines - they are can't be the same.

**Comment by timfel** [comment] 2021-11-24 09:34
This is fixed on master, we do less agressive checksumming now

**Closed by timfel** 2021-11-24 09:34 UTC
