### ISSUE TITLE
Mission intro doesn't finish voice

### ISSUE THREAD

**Issue by MarkusRamikin** [Wargus/wargus#184] opened 2016-07-02 10:36 UTC
"Betrayal and the Destruction of Alterac" - the mission intro's narration cuts off halfway. After "in hopes of concealing the Orcish mining facility located there", the text keeps scrolling, but instead of more voice, I get random in-mission music.

These mission intros are classic pieces of over-the-top voice acting awesomeness, so this is a damn shame.

(Wargus 2.4, Stratagus 2.4, Windows 7, Warcraft files installed from a DoS/W95 version)

**Comment by timfel** [comment] 2021-06-20 19:32
Duplicate of https://github.com/Wargus/wargus/issues/127

**Closed** 2021-06-20 19:32 UTC
Labels: High
