### ISSUE TITLE
Units can not pass over dead bodies after loading a save

### ISSUE THREAD

**Issue by WargusUser** [Wargus/wargus#315] opened 2020-02-23 17:41 UTC
I made a small modifications for "Hell" difficulty to make it playable. Also I set almost infinite animation delay (wait 999999) for dead body to prevent it from disappearing.
After loading a save units can't pass over dead bodies. The attached savegame works on stable wargus 2.4.2, so you don't need my modifications to lua scripts to load a savegame
[game.sav.gz](https://github.com/Wargus/wargus/files/4241898/game.sav.gz)

**Comment by timfel** [comment] 2020-06-24 21:21
I can reproduce it, but I'm at a loss why it happens. From the savegame, it looks like it knows that the unit should be dying, but it's waiting an infinite amount of time to make it actually die. I think the problem is that when we load a savegame, we don't actually save dead bodies - we save the original unit that was there and store "your next action will be to die". But if there's an unbreakable animation going on (like in the case of dead bodies), it also saves that and tries to finish it. In your case that means it will now wait 9999999 cycles before "killing" the unit again and removing it from the game.

**Comment by timfel** [comment] 2020-06-24 21:21
I'm not sure how to fix that. Our assumption was always that the last state before an actual death is a "wait 1" (or some other very short wait)

**Comment by timfel** [comment] 2020-11-29 07:23
I am willing to call this a limitation we won't fix anytime soon. Death animation simply has to be short. If you want dead bodies forever, you should instead edit the animation to "spawn-unit" a special dead body unit that is defined as passable terrain. (see, for an example, roads in War1gus)

**Closed by timfel** 2020-11-29 07:23 UTC
