### ISSUE TITLE
Can't load the graphic 'ui/scroll.png'

### ISSUE THREAD

**Issue by khronosschoty** [Wargus/wargus#260] opened 2017-12-27 17:25 UTC
For some reason when i try to load a campaign game it crashes with:

> Can't load the graphic 'ui/scroll.png'

**Comment by khronosschoty** [comment] 2018-03-18 05:25
Yes, but its been a long time (or seems like it has been); and I gave up on this  -- but I will reproduce the bug again, and report back.

**Comment by Kintobor** [comment] 2019-09-04 12:36
If I remember correctly this is caused by the wrong game data being used.

There is a flag that gets set to decide whether you are using AT or WC datasets, if it is set wrong this kind of crash occurs.

**Comment by timfel** [comment] 2020-06-09 07:36
The FtM campaigns and tales dataset has been removed on master and will be in its own package going forward.

**Closed by timfel** 2020-06-09 07:36 UTC
