### ISSUE TITLE
Please provide RPM for RPM based Linux distributions

### ISSUE THREAD

**Issue by bes1002t** [Wargus/wargus#351] opened 2021-03-24 20:25 UTC
Currently it is possible to install wargus in Ubuntu, but not with RPM based distributions.
For instance Fedora and DNF would be very good, because in the last years the Fedora community has increased a lot.

Would it be an option to build RPMs for Fedora and maybe other RPM based distributions?

**Comment by timfel** [comment] 2021-03-24 21:22
Hi,

there are packages for OpenSUSE, and some other people also requested packages for Fedora. However, I don't use Fedora and none of the maintainers currently do. So we need someone who uses Fedora to contribute this feature.

This is a duplicate of https://github.com/Wargus/stratagus/issues/214, which was closed because no one came in to do it. I will keep this issue open for a while, but unless someone comes and does it, it won't happen.

**Comment by timfel** [comment] 2021-06-20 19:40
Closing, since no one has stepped up to do it.

**Closed by timfel** 2021-06-20 19:40 UTC
